apiVersion: v1
kind: Service
metadata:
  name: payara-micro
  labels:
    name: payara
spec:
  type: NodePort
  ports:
    # The port that this service should serve on
  - port: 8080
    # the port where application will be exposed on
    nodePort: 30001
  selector:
    name: payara
